#!/usr/bin/env bash
# gen-ref.sh -- render the Faust references of the choir plugin and of the
# _common libraries it added (seam_svf.h, seam_analyzers.h) into tests/ref/.
# Run by hand when the spec changes; the tests read the committed headers
# and need no faust binary. Uses LMO's refdump (impulse or zero input).
#
# FAUSTLIBS: faustlibraries clone (0965ea2 or later)
# SEAMLIBS:  faust-libraries/src (seam.tedesco.lib)
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../../../.." && pwd)"
FAUSTLIBS="${FAUSTLIBS:-/Users/giuseppe/Documents/github/grame/faustlibraries}"
SEAMLIBS="${SEAMLIBS:-$(cd "$ROOT/../faust-libraries/src" && pwd)}"
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT
mkdir -p "$ROOT/tests/ref"

render() { # dsp sr n name input [skip]
    faust -I "$FAUSTLIBS" -I "$SEAMLIBS" -double -lang cpp -cn Ref "$HERE/dsp/$1" -o "$WORK/ref.h"
    c++ -std=c++17 -O1 -I "$WORK" "$HERE/../lmo-plugin/refdump.cpp" -o "$WORK/refdump"
    "$WORK/refdump" "$2" "$3" "$4" "$5" "${6:-0}"
}
banner() {
    echo "// GENERATED by doc/study/sscdo2/choir-plugin/gen-ref.sh -- do not edit."
    echo "// $(faust --version | head -1); faustlibraries $(git -C "$FAUSTLIBS" rev-parse --short HEAD);"
    echo "// faust-libraries $(git -C "$SEAMLIBS" rev-parse --short HEAD)."
    echo "#pragma once"
}

OUT="$ROOT/tests/ref/seam_svf_ref.h"
{ banner; echo "namespace svfref {"
  render svf48.dsp 96000 2048 kSvf48 impulse
  render svf1k.dsp 48000 512  kSvf1k impulse
  echo "} // namespace svfref"; } > "$OUT"
echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
