#!/usr/bin/env bash
# gen-ref.sh -- render the Faust references of the LMO plugin into
# tests/ref/lmo_ref.h. Run by hand when the spec changes; the tests read the
# committed header and need no faust binary.
#
# FAUSTLIBS: faustlibraries clone >= 0965ea2 (SVF fi.highpass/lowpass)
# SEAMLIBS:  faust-libraries/src (seam.tedesco.lib)
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../../../.." && pwd)"
FAUSTLIBS="${FAUSTLIBS:-/Users/giuseppe/Documents/github/grame/faustlibraries}"
SEAMLIBS="${SEAMLIBS:-$(cd "$ROOT/../faust-libraries/src" && pwd)}"
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT
OUT="$ROOT/tests/ref/lmo_ref.h"
mkdir -p "$(dirname "$OUT")"

render() { # dsp sr n name input [skip]
    faust -I "$FAUSTLIBS" -I "$SEAMLIBS" -double -lang cpp -cn Ref "$HERE/dsp/$1" -o "$WORK/ref.h"
    c++ -std=c++17 -O1 -I "$WORK" "$HERE/refdump.cpp" -o "$WORK/refdump"
    "$WORK/refdump" "$2" "$3" "$4" "$5" "${6:-0}"
}

{
    echo "// GENERATED by doc/study/sscdo2/lmo-plugin/gen-ref.sh -- do not edit."
    echo "// $(faust --version | head -1); faustlibraries $(git -C "$FAUSTLIBS" rev-parse --short HEAD);"
    echo "// faust-libraries $(git -C "$SEAMLIBS" rev-parse --short HEAD)."
    echo "#pragma once"
    echo "namespace lmoref {"
    render noise8.dsp 96000 512  kNoise8 zero
    render choirnoise.dsp 96000 128 kChoirNoise zero
    render bw.dsp     96000 2048 kBw     impulse
    render lmo.dsp    96000 2048 kLmo96  zero 96000
    render lmo.dsp    48000 1024 kLmo48  zero 48000
    echo "} // namespace lmoref"
} > "$OUT"
echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
