// GENERATED by tools/emit_header.py from coeffs.json — do not edit by hand.
// Quadrature all-pass pair, designed at fs=48000.0 Hz,
// band 20.0–20000.0 Hz, max phase error 1.3615 deg.
#pragma once
namespace Seam { namespace x2uhj {
struct APSpec { double f; double Q; };
static constexpr APSpec kHR[] = {
    { 141.887012, 0.201947 },
    { 671.745773, 0.212154 },
    { 18654.238494, 0.303097 }
};
static constexpr APSpec kHI[] = {
    { 24.003923, 0.309038 },
    { 2991.937233, 0.384766 },
    { 3219.986192, 0.096342 }
};
static constexpr int kNumSections = 3;
} } // namespace
