"""Generate x2uhj_coeffs.h from coeffs.json (single source of truth)."""
import json

with open("coeffs.json") as fp:
    d = json.load(fp)

# Both networks must have the same section count: kNumSections is shared by the
# C++ QuadratureNetwork::set for H_R and H_I alike.
assert len(d["H_R"]) == len(d["H_I"]), "H_R and H_I must have equal section counts"

def fmt(sections):
    return ",\n".join(f"    {{ {s['f']:.6f}, {s['Q']:.6f} }}" for s in sections)

text = f"""// GENERATED by tools/emit_header.py from coeffs.json — do not edit by hand.
// Quadrature all-pass pair, designed at fs={d['fs_design']} Hz,
// band {d['band'][0]}–{d['band'][1]} Hz, max phase error {d['max_error_deg']:.4f} deg.
#pragma once
namespace Seam {{ namespace x2uhj {{
struct APSpec {{ double f; double Q; }};
static constexpr APSpec kHR[] = {{
{fmt(d['H_R'])}
}};
static constexpr APSpec kHI[] = {{
{fmt(d['H_I'])}
}};
static constexpr int kNumSections = {len(d['H_R'])};
}} }} // namespace
"""
with open("../source/x2uhj_coeffs.h", "w") as fp:
    fp.write(text)
print("wrote ../source/x2uhj_coeffs.h")
