#!/usr/bin/env bash
# gen-ref.sh -- render the Faust references of the stunedrev plugin into
# tests/ref/stunedrev_ref.h. Run by hand when the spec changes; the tests
# read the committed header and need no faust binary.
#
# FAUSTLIBS: faustlibraries clone
# SEAMLIBS:  faust-libraries/src (seam.tedesco.lib; h/nextprime.h for sff.np)
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../../../.." && pwd)"
FAUSTLIBS="${FAUSTLIBS:-/Users/giuseppe/Documents/github/grame/faustlibraries}"
SEAMLIBS="${SEAMLIBS:-$(cd "$ROOT/../faust-libraries/src" && pwd)}"
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT
OUT="$ROOT/tests/ref/stunedrev_ref.h"
MOUT="$ROOT/tests/ref/seam_moorer_ref.h"
mkdir -p "$(dirname "$OUT")"

build() { # dsp
    faust -I "$FAUSTLIBS" -I "$SEAMLIBS" -double -lang cpp -cn Ref "$HERE/dsp/$1" -o "$WORK/ref.h"
    c++ -std=c++17 -O2 -I "$WORK" -I "$SEAMLIBS/h" -I "$ROOT/tests" "$HERE/refdump.cpp" -o "$WORK/refdump"
}

{
    echo "// GENERATED by doc/study/sscdo2/stunedrev-plugin/gen-ref.sh -- do not edit."
    echo "// $(faust --version | head -1); faustlibraries $(git -C "$FAUSTLIBS" rev-parse --short HEAD);"
    echo "// faust-libraries $(git -C "$SEAMLIBS" rev-parse --short HEAD)."
    echo "#pragma once"
    echo "namespace stunedrevref {"
    build stdel.dsp
    "$WORK/refdump" stdel 96000 kStdel96
    "$WORK/refdump" stdel 48000 kStdel48
    build stunedrev.dsp
    "$WORK/refdump" windows 96000 30 kWin96
    "$WORK/refdump" windows 48000 30 kWin48
    "$WORK/refdump" windows 96000 3 kChange96 48128 t3 9
    echo "} // namespace stunedrevref"
} > "$OUT"
echo "wrote $OUT ($(wc -c < "$OUT") bytes)"

{
    echo "// GENERATED by doc/study/sscdo2/stunedrev-plugin/gen-ref.sh -- do not edit."
    echo "// $(faust --version | head -1); faust-libraries $(git -C "$SEAMLIBS" rev-parse --short HEAD)."
    echo "#pragma once"
    echo "namespace moorerref {"
    build apfv.dsp
    "$WORK/refdump" impulse 96000 512 kApfv
    build apfv07.dsp
    "$WORK/refdump" impulse 96000 512 kApfv07
    echo "} // namespace moorerref"
} > "$MOUT"
echo "wrote $MOUT"
