#!/usr/bin/env python3
"""analyze.py -- delRM block 3: the triple product and its integrator.

usage (from this folder, after ./build.sh, with the seam-ltm venv):
    ../../../../.venv/bin/python analyze.py [selftest|measure|render|all] [SOURCE.wav]

SOURCE defaults to CCB_petalonio_oriz_DO.wav on the MDAGIFT volume (track 1,
the microphone at 1 m, 96 kHz). Every number comes from an executed binary.
"""
import math
import os
import subprocess
import sys

import numpy as np
import soundfile as sf
from scipy import signal

HERE = os.path.dirname(os.path.abspath(__file__))
BIN = os.path.join(HERE, "build", "bin")
WORK = os.path.join(HERE, "build", "work")
RENDERS = os.path.join(HERE, "renders")
RESULTS_MD = os.path.join(HERE, "results.md")
os.makedirs(WORK, exist_ok=True)
SRC = sys.argv[2] if len(sys.argv) > 2 else "/Volumes/MDAGIFT/CCB_petalonio_oriz_DO.wav"

DC = 3.22e-6            # the mean of track 1, measured: the offset of the real chain
FLOOR_DBFS = -70.0      # microphone and preamp floor while nobody plays
DRIFT_S = 600           # ten minutes
PRE_NOTE_S = 300        # five minutes of floor before the note, for the drifted renders
COMMANDS = []


def run(probe, sr, seconds, inp, pre=0.0, **kw):
    out = os.path.join(WORK, f"y_{os.getpid()}.f64")
    n = int(round(seconds * sr))
    args = [os.path.join(BIN, probe), str(sr), str(n), f"out={out}", f"pre={pre}", f"in=file:{inp}"]
    args += [f"{k}={v}" for k, v in kw.items()]
    COMMANDS.append(" ".join(os.path.relpath(a, HERE) if a.startswith(HERE) else a for a in args))
    subprocess.run(args, check=True, capture_output=True)
    y = np.fromfile(out)
    os.remove(out)
    return y


def rms_db(y):
    return 20 * math.log10(max(math.sqrt(float(np.mean(y ** 2))), 1e-300))


# ---- inputs --------------------------------------------------------------------------
def note(sr):
    x, fs = sf.read(SRC, dtype="float64")
    x = x[:, 0]
    x = x[: np.nonzero(x)[0][-1] + 1]
    if sr != fs:
        x = signal.resample_poly(x, sr, fs)
    return x


def floor_noise(sr, seconds, seed):
    rng = np.random.default_rng(seed)
    return rng.normal(0, 10 ** (FLOOR_DBFS / 20), int(seconds * sr)) + DC


def file_of(name, x):
    p = os.path.join(WORK, name)
    if not os.path.exists(p):
        np.asarray(x, dtype=np.float32).tofile(p)
    return p


def inputs(sr):
    x = note(sr)
    return {
        "note": (file_of(f"note{sr}.f32", x), len(x) / sr),
        "drift": file_of(f"drift{sr}.f32", floor_noise(sr, DRIFT_S + 1, 1)),
        "late": (file_of(f"late{sr}.f32", np.concatenate([floor_noise(sr, PRE_NOTE_S, 2), x])), len(x) / sr),
    }


STEADY = (0.5, 3.0)     # the sustained part of the note, seconds


def steady(y, sr):
    return y[int(STEADY[0] * sr): int(STEADY[1] * sr)]


# ---- self-test ------------------------------------------------------------------------
def selftest():
    ok = True

    def expect(name, errs, should_fail):
        nonlocal ok
        good = bool(errs) == should_fail
        ok &= good
        print(f"  [{'ok' if good else 'WRONG'}] {name}: {'FAIL' if errs else 'pass'}"
              f"{' (expected FAIL)' if should_fail else ''} {'; '.join(errs)}")

    i48, i96 = inputs(48000), inputs(96000)

    def sr_check(probe):
        a = rms_db(steady(run(probe, 48000, i48["note"][1], i48["note"][0]), 48000))
        b = rms_db(steady(run(probe, 96000, i96["note"][1], i96["note"][0]), 96000))
        return [f"96 kHz {b - a:+.2f} dB re 48 kHz, expected within 0.5"] if abs(b - a) > 0.5 else []

    expect("I1: level before the compressor independent of the rate", sr_check("pre1"), False)
    expect("I0 (original): same check", sr_check("pre0"), True)

    ref = math.sqrt(float(np.mean(steady(run("int1", 48000, i48["note"][1], i48["note"][0]), 48000) ** 2)))

    def bounded(probe):
        y = run(probe, 48000, 1.0, i48["drift"], pre=DRIFT_S - 1)
        s = float(np.max(np.abs(y)))
        return [f"|state| {s:.3g} after {DRIFT_S} s of floor and DC, above 0.1x the note's integral ({ref:.3g})"] if s > 0.1 * ref else []

    expect("I1: state stays small after ten minutes of floor and DC", bounded("int1"), False)
    expect("I0 (original): same check", bounded("int0"), True)
    print("SELFTEST", "OK" if ok else "FAILED")
    return ok


# ---- measurements ---------------------------------------------------------------------
def measure():
    L = []
    A = L.append
    A("# delRM block 3 — results")
    A("")
    A("Generated by `analyze.py measure`; overwritten on every run. Double precision.")
    A(f"Note: track 1 of `{os.path.basename(SRC)}` (1 m, 96 kHz native, resampled to 48 kHz); its steady part {STEADY[0]}–{STEADY[1]} s.")
    A(f"Floor: Gaussian noise at {FLOOR_DBFS:.0f} dBFS plus a DC of {DC:.2e}, the mean measured on track 1.")
    A("I1 is shown with fc = 1 Hz unless stated.")
    A("")
    A("## A — the integrator's state on the floor alone")
    A("")
    A("Largest |state| in the last second before each time.")
    A("")
    times = [1, 10, 60, 300, 600]
    A("| integrator | rate | " + " | ".join(f"{t} s" for t in times) + " |")
    A("|---|---|" + "---|" * len(times))
    for sr in (48000, 96000):
        inp = inputs(sr)["drift"]
        for probe, name, kw in (("int0", "I0 original", {}), ("int2", "I2 DC-blocked", {}),
                                ("int1", "I1 leaky, fc 1 Hz", {"fc": 1}), ("int1", "I1 leaky, fc 5 Hz", {"fc": 5})):
            cells = []
            for t in times:
                y = run(probe, sr, 1.0, inp, pre=t - 1, **kw)
                cells.append(f"{float(np.max(np.abs(y))):.3g}")
            A(f"| {name} | {sr // 1000} kHz | " + " | ".join(cells) + " |")
    A("")
    A("For scale, the integral of the note itself (RMS of `int1` on its steady part, 48 kHz): "
      f"{math.sqrt(float(np.mean(steady(run('int1', 48000, inputs(48000)['note'][1], inputs(48000)['note'][0]), 48000) ** 2))):.3g}.")
    A("")
    A("## B — level before the compressor, fresh start")
    A("")
    A("RMS dBFS of `pre` (10 · x[n−D] · x · I(x)) on the steady part of the note, D = 7.291 m.")
    A("")
    A("| integrator | 48 kHz | 96 kHz | difference |")
    A("|---|---|---|---|")
    for probe, name in (("pre0", "I0 original"), ("pre2", "I2 DC-blocked"), ("pre1", "I1 leaky, fc 1 Hz")):
        v = []
        for sr in (48000, 96000):
            i = inputs(sr)["note"]
            v.append(rms_db(steady(run(probe, sr, i[1], i[0]), sr)))
        A(f"| {name} | {v[0]:+.2f} | {v[1]:+.2f} | {v[1] - v[0]:+.2f} dB |")
    A("")
    A("## C — the note after five minutes of floor")
    A("")
    A(f"The note starts after {PRE_NOTE_S} s of floor and DC (48 kHz). "
      "r(pre, self-RM) is the correlation of the triple product with 10 · x[n−D] · x, the product without the integral: "
      "near ±1 means the integral has become a constant and the effect a plain self-ring-modulation.")
    A("")
    A("| integrator | pre RMS fresh | pre RMS after 5 min | r(pre, self-RM) fresh | r after 5 min | post RMS fresh | post RMS after 5 min |")
    A("|---|---|---|---|---|---|---|")
    i = inputs(48000)
    srm_f = steady(run("selfrm", 48000, i["note"][1], i["note"][0]), 48000)
    srm_l = steady(run("selfrm", 48000, i["late"][1], i["late"][0], pre=PRE_NOTE_S), 48000)
    for k, name in (("0", "I0 original"), ("2", "I2 DC-blocked"), ("1", "I1 leaky, fc 1 Hz")):
        pf = steady(run("pre" + k, 48000, i["note"][1], i["note"][0]), 48000)
        pl = steady(run("pre" + k, 48000, i["late"][1], i["late"][0], pre=PRE_NOTE_S), 48000)
        qf = steady(run("post" + k, 48000, i["note"][1], i["note"][0]), 48000)
        ql = steady(run("post" + k, 48000, i["late"][1], i["late"][0], pre=PRE_NOTE_S), 48000)
        A(f"| {name} | {rms_db(pf):+.1f} | {rms_db(pl):+.1f} | {np.corrcoef(pf, srm_f)[0, 1]:+.2f} | "
          f"{np.corrcoef(pl, srm_l)[0, 1]:+.2f} | {rms_db(qf):+.1f} | {rms_db(ql):+.1f} |")
    A("")
    A("## Commands run")
    A("")
    A("```")
    seen = set()
    for c in COMMANDS:
        if c.split()[0] not in seen:
            seen.add(c.split()[0])
            A(c)
    A("```")
    A("")
    NOTES = "<!-- hand-written notes below this line are preserved by analyze.py -->"
    old = open(RESULTS_MD).read() if os.path.exists(RESULTS_MD) else ""
    notes = old.split(NOTES, 1)[1] if NOTES in old else "\n"
    with open(RESULTS_MD, "w") as fh:
        fh.write("\n".join(L) + "\n" + NOTES + notes)
    print("\n".join(L))


# ---- renders --------------------------------------------------------------------------
def render():
    sr = 48000
    i = inputs(sr)
    log = []

    def write(name, y):
        n = int(0.02 * sr)
        w = 0.5 - 0.5 * np.cos(np.pi * np.arange(n) / n)
        y = y.copy(); y[:n] *= w; y[-n:] *= w[::-1]
        g = 10 ** (-20 / 20) / math.sqrt(float(np.mean(y ** 2)))
        y = y * g
        sf.write(os.path.join(RENDERS, name), y, sr, subtype="PCM_24")
        log.append(f"| {name} | {20 * math.log10(g):+.2f} |")

    write("note_dry.wav", note(sr))
    for k, tag in (("0", "I0-original"), ("1", "I1-leaky-1Hz"), ("2", "I2-dcblocked")):
        write(f"post_{tag}_fresh.wav", run("post" + k, sr, i["note"][1], i["note"][0]))
        write(f"post_{tag}_after5min.wav", run("post" + k, sr, i["late"][1], i["late"][0], pre=PRE_NOTE_S))
    write("selfrm_post.wav", run("selfrm", sr, i["note"][1], i["note"][0]))
    with open(os.path.join(RENDERS, "render-log.md"), "w") as fh:
        fh.write("48 kHz, 24-bit, every file normalised to -20 dBFS RMS (20 ms fades); "
                 "the gain column is what normalisation applied.\n\n| file | gain dB |\n|---|---|\n" + "\n".join(log) + "\n")
    print("\n".join(log))


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "all"
    if cmd in ("selftest", "all") and not selftest():
        sys.exit(1)
    if cmd in ("measure", "all"):
        measure()
    if cmd in ("render", "all"):
        render()
