#!/usr/bin/env bash
# gen-ref.sh -- render the Faust references of the delRM plugin and of the
# _common libraries it added (seam_filters.h, seam_compressors.h) into
# tests/ref/. Run by hand when the spec changes; the tests read the
# committed headers and need no faust binary.
#
# FAUSTLIBS: faustlibraries clone (0965ea2 or later)
# SEAMLIBS:  faust-libraries/src (seam.tedesco.lib; h/nextprime.h for sff.np)
set -euo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../../../.." && pwd)"
FAUSTLIBS="${FAUSTLIBS:-/Users/giuseppe/Documents/github/grame/faustlibraries}"
SEAMLIBS="${SEAMLIBS:-$(cd "$ROOT/../faust-libraries/src" && pwd)}"
WORK="$(mktemp -d)"; trap 'rm -rf "$WORK"' EXIT
mkdir -p "$ROOT/tests/ref"

build() { # dsp
    faust -I "$FAUSTLIBS" -I "$SEAMLIBS" -double -lang cpp -cn Ref "$HERE/dsp/$1" -o "$WORK/ref.h"
    c++ -std=c++17 -O2 -I "$WORK" -I "$SEAMLIBS/h" -I "$ROOT/tests" "$HERE/refdump.cpp" -o "$WORK/refdump"
}
banner() {
    echo "// GENERATED by doc/study/sscdo2/delrm-plugin/gen-ref.sh -- do not edit."
    echo "// $(faust --version | head -1); faustlibraries $(git -C "$FAUSTLIBS" rev-parse --short HEAD);"
    echo "// faust-libraries $(git -C "$SEAMLIBS" rev-parse --short HEAD)."
    echo "#pragma once"
}

OUT="$ROOT/tests/ref/seam_filters_ref.h"
{ banner; echo "namespace filtersref {"
  build leakyint.dsp
  "$WORK/refdump" 96000 2 kLeaky96
  "$WORK/refdump" 48000 2 kLeaky48
  echo "} // namespace filtersref"; } > "$OUT"
echo "wrote $OUT ($(wc -c < "$OUT") bytes)"

OUT="$ROOT/tests/ref/seam_compressors_ref.h"
{ banner; echo "namespace compressorsref {"
  build comp.dsp
  "$WORK/refdump" 96000 2 kComp96
  build comp2.dsp
  "$WORK/refdump" 96000 2 kComp2_96
  echo "} // namespace compressorsref"; } > "$OUT"
echo "wrote $OUT ($(wc -c < "$OUT") bytes)"

OUT="$ROOT/tests/ref/delrm_ref.h"
{ banner; echo "namespace delrmref {"
  build delrm.dsp
  "$WORK/refdump" 96000 2 kWin96
  "$WORK/refdump" 48000 2 kWin48
  "$WORK/refdump" 96000 2 kChange96 96000 mt 10
  echo "} // namespace delrmref"; } > "$OUT"
echo "wrote $OUT ($(wc -c < "$OUT") bytes)"
